name: Android

on:
  push:
    branchs:
      - main
      - master 
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install && yarn
      - run: npm ci
      - run: npx jetifier
      - run: ./gradlew assembleRelease
        working-directory: android
        name: apk aturPOS

      - uses: actions/upload-artifact@v2
        with:
          name: aturPOS-apk
          path: '**/*.apk'